global_costmap:
  global_frame: map
  robot_base_frame: base_link
  publish_frequency: 2.0
  update_frequency: 5.0
  transform_tolerance: 0.5
  static_map: false
  rolling_window: true #..
  resolution: 0.05
  width: 12.0
  height: 12.0
 plugins:
    

     # - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
